nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  devmemoryLimits: 1024Mi
  devmemoryRequests: 512Mi
  keyVaults:
    et:
      resourceGroup: et
      secrets:
        - AppInsightsInstrumentationKey
        - idam-secret
        - name: redis-access-key
          alias: et-syr-redis-access-key
        - os-places-token
        - pcq-token-key
        - launch-darkly-sdk-key
  environment:
    REDIS_HOST: 'et-sya-session-storage-aat.redis.cache.windows.net'
idam-pr:
  enabled: true
  redirect_uris:
    ET Citizen Submit Your Appeal:
      - https://${SERVICE_FQDN}/oauth2/callback
